name: build-wix-test-msis

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install WiX Toolset v3.11
        shell: powershell
        run: |
          choco install wixtoolset --version=3.11.2 -y
          echo "C:\\Program Files (x86)\\WiX Toolset v3.11\\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          candle.exe -?
          light.exe -?

      - name: Build WiX test MSIs
        shell: powershell
        run: |
          cd tests\\wix
          ./build.ps1

      - name: Upload MSIs
        uses: actions/upload-artifact@v4
        with:
          name: wix-test-msis
          path: tests/wix/out/*.msi
